### ISSUE TITLE
Organize the docs

### ISSUE THREAD

**Issue by tremblerz** [aidecentralized/sonar#22]
Our documentation is hosted on https://aidecentralized.github.io/sonar/ and uses MKDocs (thanks to @ishaansingh22 )
The documentation serves two purpose - 1) How to run/modify the code, and 2) Benchmark (Leaderboard for decentralized collaborative learning algorithms). Going forward, we also want to enable the third capability -- Instructions on how to deploy and/or join the network.

We need to do a lot of UI/UX improvement and make the documentation comprehensive. More details to follow but it would be great if someone can get started on this.

**Comment by gautamjajoo** [comment]
Some improvements that are top of my mind:

- [ ] Add a table of content
- [ ] Instead of sections on one page, we can have a documentation directory with different pages
