### ISSUE TITLE
Create a separate data loader file for each dataset

### ISSUE THREAD

**Issue by tremblerz** [aidecentralized/sonar#7]
Right now `data_utils.py` file is trying to import all the data loader libraries and files. Due to this centralization of loaders, we have to install all unnecessary data loader libraries even though we aren't going to use most of them. A better organization of data_utils so that only required libs are loaded will be a better solution. It is not trivial because libraries will have to be loaded dynamically. However, this is something we have already done for our config loaders.

**Comment by hardlyhuman** [comment]
@tremblerz I can work on this. The high-level approach I can think as of now is to separate all the classes into different files and import the necessary classes using 'importlib'. Please let me know if this approach matches thoughts/expectations

**Comment by tremblerz** [comment]
Sounds great! Please go ahead with it
