### ISSUE TITLE
Multiple Errors: AttributeError and NameError in resnet module and CIFAR10Dataset

### ISSUE THREAD

**Issue by nikitaparate** [aidecentralized/sonar#8]
Encountering multiple errors when trying to run the main.py script with the resnet module and CIFAR10Dataset. Below are the details of each error:

Errors:
1. AttributeError: module 'resnet' has no attribute 'ResNet34'. Did you mean: 'resnet34'?
2. AttributeError: 'CIFAR10Dataset' object has no attribute 'NUM_CLS'
3. NameError: name 'FedRanServer' is not defined. Did you mean: 'FedValServer'?

**Comment by gautamjajoo** [comment]
Sorry for being late here. I guess this issue has been resolved in https://github.com/aidecentralized/sonar/pull/9.

Regarding the third point, we shifted to `fl_static` from the `ring`, `random` etc. Didn't remove it from `scheduler` my bad. We can remove them.

**Comment by tremblerz** [comment]
@gautamjajoo can you confirm this is fixed? We can close the issue then.

**Comment by gautamjajoo** [comment]
Yes, the issue has been fixed
